### ISSUE TITLE
USB Boot mode

### ISSUE THREAD

**Issue by dcarb** [Blueforcer/Quest_Updater#1]
Hi and thanks for your job.

when i restart to usb mode update. The program nothing... I need to select enable sideloading update? thanks for your return

**Comment by Blueforcer** [comment]
You dont need to boot your quest into any special mode. Just start it normaly and run the bat file.

**Comment by dcarb** [comment]
when i'm on update mode, it's just stay on "wait oem" and it does nothing...

**Comment by Blueforcer** [comment]
please post the output of the terminal window.. is there any Error message i need to know?
Do you enabled developer mode?

**Comment by dcarb** [comment]
Sorry I just see your response. I will post tomorrow.
